# When adding or removing cuda versions, make sure that the following entries are "zipped";
# e.g. each entry in cuda_compiler_version must have a matching entry in the other keys,
# considering the effect of the selector:
#   cuda_compiler_version
#   cudnn
#   cdt_name
#   docker_image

zip_keys:
  - - cuda_compiler_version   # [linux64 or ppc64le]
    - cdt_name                # [linux64 or ppc64le]
    - docker_image            # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
    - docker_image            # [ppc64le and os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
    - cudnn                   # [linux64 or ppc64le]

docker_image:                                       # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-comp7           # [os.environ.get("BUILD_PLATFORM") == "linux-64"]
   - quay.io/condaforge/linux-anvil-cos7-x86_64     # [os.environ.get("BUILD_PLATFORM") == "linux-64"]
   - quay.io/condaforge/linux-anvil-ppc64le         # [os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]

   - quay.io/condaforge/linux-anvil-cuda:10.1       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:10.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.0       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.1       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.2       # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

   - quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2   # [ppc64le and os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]

c_compiler_version:     # [linux]
  - 7                   # [linux64]
  - 8                   # [ppc64le]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64]
  - 8                   # [ppc64le]

cuda_compiler:   # [linux]
  - nvcc         # [linux]

cuda_compiler_version:
  - None                       # [linux64]
  - None                       # [linux64 or ppc64le]
  - 10.1                       # [linux64]
  - 10.2                       # [linux64 or ppc64le]
  - 11.0                       # [linux64]
  - 11.1                       # [linux64]
  - 11.2                       # [linux64]

cudnn:
  - undefined                  # [linux64]
  - undefined                  # [linux64 or ppc64le]
  - 7                          # [linux64]  # CUDA 10.1
  - 7                          # [linux64]  # CUDA 10.2
  - 8                          # [linux64]  # CUDA 11.0
  - 8                          # [linux64]  # CUDA 11.1
  - 8                          # [linux64]  # CUDA 11.2

  # TODO: fix this once https://github.com/conda-forge/cudnn-feedstock/issues/18 is fixed
  - undefined                  # [ppc64le]

cdt_name:  # [linux]
  - cos6   # [linux64]
  - cos7   # [linux64 or ppc64le]
  - cos6   # [linux64]
  - cos6   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]

  - cos7   # [ppc64le]
